//newletter
export const JOIN_MAILING_LIST_REQUEST = 'JOIN_MAILING_LIST_REQUEST';
export const JOIN_MAILING_LIST_SUCCESS = 'JOIN_MAILING_LIST_SUCCESS';
export const JOIN_MAILING_LIST_FAIL = 'JOIN_MAILING_LIST_FAIL';
