//vendors
export const CREATE_VENDOR_REQUEST = 'CREATE_VENDOR_REQUEST';
export const CREATE_VENDOR_SUCCESS = 'CREATE_VENDOR_SUCCESS';
export const CREATE_VENDOR_FAIL = 'CREATE_VENDOR_FAIL';

export const UPDATE_VENDOR_REQUEST = 'UPDATE_VENDOR_REQUEST';
export const UPDATE_VENDOR_SUCCESS = 'UPDATE_VENDOR_SUCCESS';
export const UPDATE_VENDOR_FAIL = 'UPDATE_VENDOR_FAIL';

export const DELETE_VENDOR_REQUEST = 'DELETE_VENDOR_REQUEST';
export const DELETE_VENDOR_SUCCESS = 'DELETE_VENDOR_SUCCESS';
export const DELETE_VENDOR_FAIL = 'DELETE_VENDOR_FAIL';

export const GET_VENDOR_REQUEST = 'GET_VENDOR_REQUEST';
export const GET_VENDOR_SUCCESS = 'GET_VENDOR_SUCCESS';
export const GET_VENDOR_FAIL = 'GET_VENDOR_FAIL';

export const GET_MY_VENDOR_REQUEST = 'GET_MY_VENDOR_REQUEST';
export const GET_MY_VENDOR_SUCCESS = 'GET_MY_VENDOR_SUCCESS';
export const GET_MY_VENDOR_FAIL = 'GET_MY_VENDOR_FAIL';

export const INVITE_A_FRIEND_REQUEST = 'INVITE_A_FRIEND_REQUEST';
export const INVITE_A_FRIEND_SUCCESS = 'INVITE_A_FRIEND_SUCCESS';
export const INVITE_A_FRIEND_FAIL = 'INVITE_A_FRIEND_FAIL';

export const SUGGEST_A_STORE_REQUEST = 'SUGGEST_A_STORE_REQUEST';
export const SUGGEST_A_STORE_SUCCESS = 'SUGGEST_A_STORE_SUCCESS';
export const SUGGEST_A_STORE_FAIL = 'SUGGEST_A_STORE_FAIL';

export const GET_VENDORS_REQUEST = 'GET_VENDORS_REQUEST';
export const GET_VENDORS_SUCCESS = 'GET_VENDORS_SUCCESS';
export const GET_VENDORS_FAIL = 'GET_VENDORS_FAIL';

export const GET_VENDORS_BY_CATERGORY_REQUEST =
    'GET_VENDORS_BY_CATERGORY_REQUEST';
export const GET_VENDORS_BY_CATERGORY_SUCCESS =
    'GET_VENDORS_BY_CATERGORY_SUCCESS';
export const GET_VENDORS_BY_CATERGORY_FAIL = 'GET_VENDORS_BY_CATERGORY_FAIL';

export const FOLLOW_VENDOR_REQUEST = 'FOLLOW_VENDOR_REQUEST';
export const FOLLOW_VENDOR_SUCCESS = 'FOLLOW_VENDOR_SUCCESS';
export const FOLLOW_VENDOR_FAIL = 'FOLLOW_VENDOR_FAIL';

export const UNFOLLOW_VENDOR_REQUEST = 'UNFOLLOW_VENDOR_REQUEST';
export const UNFOLLOW_VENDOR_SUCCESS = 'UNFOLLOW_VENDOR_SUCCESS';
export const UNFOLLOW_VENDOR_FAIL = 'UNFOLLOW_VENDOR_FAIL';
